<template>
  <div class="top-content-card" @click="$emit('content-click', content)">
    <div class="card-header">
      <div class="performance-badge" :class="getPerformanceBadgeClass(content.performanceScore)">
        <i class="pi pi-star"></i>
        <span>{{ getPerformanceRating(content.performanceScore) }}</span>
      </div>
      <div class="ai-provider-badge">
        <i :class="getProviderIcon(content.aiProvider)"></i>
        <span>{{ formatProviderName(content.aiProvider) }}</span>
      </div>
    </div>
    
    <div class="card-content">
      <div class="content-headline">
        <h4 class="headline-text">{{ content.headline }}</h4>
        <div class="content-id">#{{ content.contentId }}</div>
      </div>
      
      <div class="performance-metrics">
        <div class="metric-row">
          <div class="metric-item">
            <i class="pi pi-eye"></i>
            <span class="metric-label">Impressions</span>
            <span class="metric-value">{{ formatNumber(content.impressions) }}</span>
          </div>
          <div class="metric-item">
            <i class="pi pi-mouse"></i>
            <span class="metric-label">CTR</span>
            <span class="metric-value">{{ content.ctr.toFixed(2) }}%</span>
          </div>
        </div>
        
        <div class="performance-score">
          <div class="score-label">Performance Score</div>
          <div class="score-bar">
            <div class="score-background">
              <div 
                class="score-fill" 
                :style="{ 
                  width: `${getScorePercentage(content.performanceScore)}%`,
                  backgroundColor: getScoreColor(content.performanceScore)
                }"
              ></div>
            </div>
            <span class="score-value">{{ Math.round(content.performanceScore) }}</span>
          </div>
        </div>
      </div>
    </div>
    
    <div class="card-footer">
      <div class="provider-info">
        <span class="provider-label">Generated by</span>
        <span class="provider-name">{{ formatProviderName(content.aiProvider) }}</span>
      </div>
      
      <div class="action-buttons">
        <button 
          @click.stop="viewDetails"
          class="action-btn view-btn"
          title="View Details"
        >
          <i class="pi pi-eye"></i>
        </button>
        <button 
          @click.stop="copyContent"
          class="action-btn copy-btn"
          title="Copy Content"
        >
          <i class="pi pi-copy"></i>
        </button>
        <button 
          @click.stop="analyzeContent"
          class="action-btn analyze-btn"
          title="Analyze Performance"
        >
          <i class="pi pi-chart-line"></i>
        </button>
      </div>
    </div>
    
    <!-- Performance Trend Indicator -->
    <div class="trend-indicator" :class="getTrendClass(content.performanceScore)">
      <i :class="getTrendIcon(content.performanceScore)"></i>
    </div>
  </div>
</template>

<script>
export default {
  name: 'TopContentCard',
  props: {
    content: {
      type: Object,
      required: true
    }
  },
  emits: ['content-click'],
  
  setup(props, { emit }) {
    // Methods
    const formatNumber = (value) => {
      if (value >= 1000000) {
        return `${(value / 1000000).toFixed(1)}M`
      } else if (value >= 1000) {
        return `${(value / 1000).toFixed(1)}K`
      }
      return value.toLocaleString()
    }
    
    const formatProviderName = (provider) => {
      if (!provider) return 'Unknown'
      return provider.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())
    }
    
    const getProviderIcon = (provider) => {
      const icons = {
        'OPENAI': 'pi pi-bolt',
        'GEMINI': 'pi pi-star',
        'ANTHROPIC': 'pi pi-brain',
        'HUGGINGFACE': 'pi pi-heart',
        'FAL_AI': 'pi pi-flash',
        'STABLE_DIFFUSION': 'pi pi-image'
      }
      return icons[provider] || 'pi pi-cog'
    }
    
    const getPerformanceRating = (score) => {
      if (score >= 8000) return 'Excellent'
      if (score >= 6000) return 'Very Good'
      if (score >= 4000) return 'Good'
      if (score >= 2000) return 'Average'
      return 'Below Average'
    }
    
    const getPerformanceBadgeClass = (score) => {
      if (score >= 8000) return 'badge-excellent'
      if (score >= 6000) return 'badge-very-good'
      if (score >= 4000) return 'badge-good'
      if (score >= 2000) return 'badge-average'
      return 'badge-poor'
    }
    
    const getScorePercentage = (score) => {
      // Normalize score to 0-100 range (assuming max score around 10000)
      return Math.min((score / 10000) * 100, 100)
    }
    
    const getScoreColor = (score) => {
      if (score >= 8000) return '#10b981' // Green
      if (score >= 6000) return '#3b82f6' // Blue
      if (score >= 4000) return '#f59e0b' // Yellow
      if (score >= 2000) return '#f97316' // Orange
      return '#ef4444' // Red
    }
    
    const getTrendClass = (score) => {
      if (score >= 6000) return 'trend-up'
      if (score >= 3000) return 'trend-stable'
      return 'trend-down'
    }
    
    const getTrendIcon = (score) => {
      if (score >= 6000) return 'pi pi-arrow-up'
      if (score >= 3000) return 'pi pi-minus'
      return 'pi pi-arrow-down'
    }
    
    const viewDetails = () => {
      emit('content-click', props.content)
    }
    
    const copyContent = () => {
      if (navigator.clipboard && props.content.headline) {
        navigator.clipboard.writeText(props.content.headline)
          .then(() => {
            // You could show a toast notification here
            console.log('Content copied to clipboard')
          })
          .catch(err => {
            console.error('Failed to copy content:', err)
          })
      }
    }
    
    const analyzeContent = () => {
      // Emit event for content analysis
      console.log('Analyze content:', props.content.contentId)
    }
    
    return {
      formatNumber,
      formatProviderName,
      getProviderIcon,
      getPerformanceRating,
      getPerformanceBadgeClass,
      getScorePercentage,
      getScoreColor,
      getTrendClass,
      getTrendIcon,
      viewDetails,
      copyContent,
      analyzeContent
    }
  }
}
</script>

<style scoped>
.top-content-card {
  position: relative;
  background: white;
  border: 1px solid #e5e7eb;
  border-radius: 12px;
  padding: 20px;
  cursor: pointer;
  transition: all 0.3s ease;
  overflow: hidden;
}

.top-content-card:hover {
  transform: translateY(-4px);
  box-shadow: 0 10px 25px -3px rgb(0 0 0 / 10%);
  border-color: #d1d5db;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 16px;
  gap: 8px;
}

.performance-badge {
  display: flex;
  align-items: center;
  gap: 4px;
  padding: 4px 8px;
  border-radius: 6px;
  font-size: 11px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.badge-excellent {
  background: #dcfce7;
  color: #166534;
}

.badge-very-good {
  background: #dbeafe;
  color: #1d4ed8;
}

.badge-good {
  background: #e0f2fe;
  color: #0369a1;
}

.badge-average {
  background: #fef3c7;
  color: #92400e;
}

.badge-poor {
  background: #fee2e2;
  color: #991b1b;
}

.ai-provider-badge {
  display: flex;
  align-items: center;
  gap: 4px;
  padding: 4px 8px;
  background: #f3f4f6;
  border-radius: 6px;
  font-size: 11px;
  color: #6b7280;
  font-weight: 500;
}

.ai-provider-badge i {
  font-size: 10px;
}

.card-content {
  margin-bottom: 16px;
}

.content-headline {
  margin-bottom: 16px;
}

.headline-text {
  font-size: 16px;
  font-weight: 600;
  color: #111827;
  line-height: 1.4;
  margin: 0 0 4px;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

.content-id {
  font-size: 12px;
  color: #9ca3af;
  font-weight: 500;
}

.performance-metrics {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.metric-row {
  display: flex;
  gap: 16px;
}

.metric-item {
  display: flex;
  align-items: center;
  gap: 6px;
  flex: 1;
}

.metric-item i {
  font-size: 14px;
  color: #6b7280;
}

.metric-label {
  font-size: 12px;
  color: #6b7280;
  font-weight: 500;
}

.metric-value {
  font-size: 14px;
  color: #111827;
  font-weight: 600;
  margin-left: auto;
}

.performance-score {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.score-label {
  font-size: 12px;
  color: #6b7280;
  font-weight: 500;
}

.score-bar {
  display: flex;
  align-items: center;
  gap: 8px;
}

.score-background {
  flex: 1;
  height: 6px;
  background: #e5e7eb;
  border-radius: 3px;
  overflow: hidden;
}

.score-fill {
  height: 100%;
  border-radius: 3px;
  transition: width 0.3s ease;
}

.score-value {
  font-size: 12px;
  color: #111827;
  font-weight: 600;
  min-width: 30px;
  text-align: right;
}

.card-footer {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 12px;
}

.provider-info {
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.provider-label {
  font-size: 11px;
  color: #9ca3af;
  font-weight: 500;
}

.provider-name {
  font-size: 12px;
  color: #6b7280;
  font-weight: 600;
}

.action-buttons {
  display: flex;
  gap: 4px;
}

.action-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 28px;
  height: 28px;
  border: none;
  border-radius: 6px;
  cursor: pointer;
  transition: all 0.2s ease;
  font-size: 12px;
}

.view-btn {
  background: #eff6ff;
  color: #2563eb;
}

.view-btn:hover {
  background: #dbeafe;
}

.copy-btn {
  background: #f0fdf4;
  color: #16a34a;
}

.copy-btn:hover {
  background: #dcfce7;
}

.analyze-btn {
  background: #fef3c7;
  color: #d97706;
}

.analyze-btn:hover {
  background: #fde68a;
}

.trend-indicator {
  position: absolute;
  top: 12px;
  right: 12px;
  width: 24px;
  height: 24px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 10px;
  font-weight: 600;
}

.trend-up {
  background: #dcfce7;
  color: #166534;
}

.trend-stable {
  background: #fef3c7;
  color: #92400e;
}

.trend-down {
  background: #fee2e2;
  color: #991b1b;
}

/* Responsive Design */
@media (width <= 640px) {
  .top-content-card {
    padding: 16px;
  }
  
  .card-header {
    flex-direction: column;
    align-items: stretch;
    gap: 8px;
  }
  
  .performance-badge,
  .ai-provider-badge {
    align-self: flex-start;
  }
  
  .metric-row {
    flex-direction: column;
    gap: 8px;
  }
  
  .card-footer {
    flex-direction: column;
    align-items: stretch;
    gap: 12px;
  }
  
  .action-buttons {
    justify-content: center;
  }
  
  .headline-text {
    font-size: 14px;
  }
  
  .trend-indicator {
    position: static;
    align-self: flex-end;
    margin-top: 8px;
  }
}

/* Animation for score bar */
@keyframes fillScore {
  from {
    width: 0;
  }

  to {
    width: var(--target-width);
  }
}

.score-fill {
  animation: fillScore 1s ease-out;
}

/* Hover effects */
.top-content-card:hover .headline-text {
  color: #3b82f6;
}

.top-content-card:hover .trend-indicator {
  transform: scale(1.1);
}

.top-content-card:hover .action-btn {
  transform: scale(1.05);
}
</style>
