package com.fbadsautomation.ai;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fbadsautomation.model.AdContent;
import com.fbadsautomation.model.Capability;
import com.fbadsautomation.model.FacebookCTA;
import java.io.IOException;
import java.io.File;
import java.io.InputStream;
import java.io.FileOutputStream;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.Collections;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

@Service
public class FalAiProvider implements AIProvider {
    
    private static final Logger log = LoggerFactory.getLogger(FalAiProvider.class);

    private final RestTemplate restTemplate;
    private final String apiKey;
    private final String apiUrl;
    private final ObjectMapper objectMapper = new ObjectMapper();
    @Value("${app.image.storage.location}")
    private String imageStorageLocation;

    public FalAiProvider(
        RestTemplate restTemplate,
        @Value("${fal.ai.api.key}") String apiKey,
        @Value("${fal.ai.api.url:https://fal.run/fal-ai/fast-sdxl}") String apiUrl) {
            this.restTemplate = restTemplate;
            this.apiKey = apiKey;
            this.apiUrl = apiUrl;
            
            log.info("Using Fal.ai API URL: {}", this.apiUrl);
    }

    @Override
    public List<AdContent> generateAdContent(String prompt, int numberOfVariations, String language, FacebookCTA callToAction) {
        // Fal.ai is primarily for image generation, so we return mock text content
        log.warn("Fal.ai does not support text generation. Returning mock data.");
        List<AdContent> adContents = new ArrayList<>();
        for (int i = 0; i < numberOfVariations; i++) {
            AdContent mockContent = new AdContent();
            mockContent.setHeadline("Mock Headline for " + prompt);
            mockContent.setDescription("Generated by Fal.ai (mock text)");
            mockContent.setPrimaryText("This is mock primary text as Fal.ai is for images.");
            mockContent.setCallToAction(callToAction != null ? callToAction : FacebookCTA.LEARN_MORE); // Đảm bảo truyền đúng kiểu
            mockContent.setCta(callToAction != null ? callToAction : FacebookCTA.LEARN_MORE); // Đảm bảo truyền đúng kiểu
            mockContent.setAiProvider(AdContent.AIProvider.FAL_AI);
            adContents.add(mockContent);
        }
        return adContents;
    }

    @Override
    public String generateImage(String prompt) {
        if (!supportsImageGeneration()) {
            log.warn("Fal.ai image generation not supported (likely missing API key).");
            return "/img/placeholder.png";
        }

        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        headers.set("Authorization", "Key " + apiKey);

        // Enhanced prompt for better commercial image quality
        String enhancedPrompt = "Professional commercial advertisement image for: " + prompt + 
            ". High quality, studio lighting, product photography, marketing style, clean background, " +
            "vibrant colors, professional composition, 4k resolution, commercial photography";

        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("prompt", enhancedPrompt);
        requestBody.put("image_size", "1024x1024");
        requestBody.put("num_inference_steps", 50);
        requestBody.put("guidance_scale", 7.5);

        HttpEntity<Map<String, Object>> request = new HttpEntity<>(requestBody, headers);
        log.debug("Calling Fal.ai API at: {} with prompt: {}", apiUrl, enhancedPrompt);

        try {
            Map<String, Object> response = restTemplate.postForObject(apiUrl, request, Map.class);
            if (response != null && response.containsKey("images")) {
                List<Map<String, Object>> images = (List<Map<String, Object>>) response.get("images");
                if (!images.isEmpty() && images.get(0).containsKey("url")) {
                    String imageUrl = (String) images.get(0).get("url");
                    log.info("Successfully received image URL from Fal.ai: {}", imageUrl);
                    try (InputStream in = new URL(imageUrl).openStream()) {
                        String filename = UUID.randomUUID().toString() + ".png";
                        Path uploadPath = Paths.get(imageStorageLocation);
                        if (!Files.exists(uploadPath)) {
                            Files.createDirectories(uploadPath);
                        }
                        Path filePath = uploadPath.resolve(filename);
                        Files.copy(in, filePath);
                        String localUrl = "/api/images/" + filename;
                        log.info("Saved Fal.ai image to local: {} | URL: {}", filePath, localUrl);
                        return localUrl;
                    } catch (Exception ex) {
                        log.error("Failed to save Fal.ai image to local: {}", ex.getMessage(), ex);
                        return "/img/placeholder.png";
                    }
                }
            } else {
                log.error("Fal.ai API call failed with response: {}", response);
            }
        } catch (Exception e) {
            log.error("Error calling Fal.ai API: {}", e.getMessage(), e);
        }

        return "/img/placeholder.png";
    }

    @Override
    public String getName() {
        return "Fal.ai";
    }

    @Override
    public String getProviderName() {
        return "Fal.ai";
    }

    @Override
    public String getApiUrl() {
        return apiUrl;
    }

    @Override
    public Set<Capability> getCapabilities() {
        return EnumSet.of(Capability.IMAGE_GENERATION, Capability.REAL_TIME);
    }

    public boolean supportsImageGeneration() {
        return apiKey != null && !apiKey.isEmpty();
    }

    private List<AdContent> generateMockAdContents(String prompt, int numberOfVariations) {
        List<AdContent> mockContents = new ArrayList<>();
        for (int i = 0; i < numberOfVariations; i++) {
            AdContent adContent = new AdContent();
            adContent.setHeadline("Fal.ai: Tiêu đề mẫu #" + (i + 1) + " cho: " + prompt);
            adContent.setDescription("Mô tả ngắn gọn cho mẫu quảng cáo Fal.ai #" + (i + 1));
            adContent.setPrimaryText("Đây là nội dung chính của mẫu quảng cáo Fal.ai #" + (i + 1) + ". Nội dung này sẽ mô tả chi tiết về sản phẩm hoặc dịch vụ được quảng cáo.");
            adContent.setCallToAction(FacebookCTA.LEARN_MORE); // Sửa: truyền FacebookCTA thay vì String
            adContent.setCta(FacebookCTA.LEARN_MORE); // Sửa: truyền FacebookCTA thay vì String
            adContent.setImageUrl("/img/placeholder.png");
            adContent.setAiProvider(AdContent.AIProvider.FAL_AI);
            adContent.setIsSelected(false);
            mockContents.add(adContent);
        }
        return mockContents;
    }
}
