package com.fbadsautomation.ai;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fbadsautomation.model.AdContent;
import com.fbadsautomation.model.Capability;
import com.fbadsautomation.model.FacebookCTA;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Collections;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

@Service
public class StableDiffusionProvider implements AIProvider {
    
    private static final Logger log = LoggerFactory.getLogger(StableDiffusionProvider.class);
    private final RestTemplate restTemplate;
    private final String apiKey;
    private final String imageApiUrl;
    private String imageStorageLocation;
    private final ObjectMapper objectMapper = new ObjectMapper();
        public StableDiffusionProvider(
            RestTemplate restTemplate,
            @Value("${ai.huggingface.api-key}") String apiKey,
            @Value("${ai.huggingface.image-api-url:https://api-inference.huggingface.co/models/stabilityai/stable-diffusion-xl-base-1.0}") String imageApiUrl,
            @Value("${app.image.storage.location:uploads/images}") String imageStorageLocation) {
        this.restTemplate = restTemplate;
        this.apiKey = apiKey;
        this.imageApiUrl = imageApiUrl;
        this.imageStorageLocation = imageStorageLocation;
        log.info("Using Stable Diffusion Image API URL: {}", this.imageApiUrl);
        
        // Ensure the image save directory exists
        try {
            Files.createDirectories(Paths.get(imageStorageLocation));
            log.info("Image save directory ensured at: {}", imageStorageLocation);
        } catch (IOException e) {
            log.error("Could not create image save directory: {}", imageStorageLocation, e);
        }
    }

    @Override
    public Set<Capability> getCapabilities() {
        Set<Capability> capabilities = EnumSet.of(Capability.IMAGE_GENERATION, Capability.REAL_TIME);
        return capabilities;
    }

    @Override
    public List<AdContent> generateAdContent(String prompt, int numberOfVariations, String language, FacebookCTA callToAction) {
        // Stable Diffusion is for image generation, so we return mock text content
        log.warn("Stable Diffusion does not support text generation. Returning mock data.");
        List<AdContent> adContents = new ArrayList<>();
        for (int i = 0; i < numberOfVariations; i++) {
            AdContent mockContent = new AdContent();
            mockContent.setHeadline("Mock Headline for " + prompt);
            mockContent.setDescription("Generated by Stable Diffusion (mock text)");
            mockContent.setPrimaryText("This is mock primary text as Stable Diffusion is for images.");
            mockContent.setCallToAction(callToAction);
            mockContent.setCta(callToAction);
            mockContent.setAiProvider(AdContent.AIProvider.STABLE_DIFFUSION);
            adContents.add(mockContent);
        }
        return adContents;
    }

    @Override
    public String generateImage(String prompt) {
        if (!supportsImageGeneration()) {
            log.warn("Stable Diffusion image generation not supported (likely missing API key).");
            return "/img/placeholder.png";
        }

        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        headers.setAccept(Collections.singletonList(MediaType.APPLICATION_OCTET_STREAM));
        headers.set("Authorization", "Bearer " + apiKey);

        // Enhanced prompt for better commercial image quality
        String enhancedPrompt = "Professional commercial advertisement image for: " + prompt +
            ". High quality, studio lighting, product photography, marketing style, clean background, " +
            "vibrant colors, professional composition, 4k resolution, commercial photography";
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("inputs", enhancedPrompt);
        requestBody.put("parameters", Map.of(
            "num_inference_steps", 50,
            "guidance_scale", 7.5,
            "width", 1024,
            "height", 1024
        ));
        requestBody.put("options", Map.of("wait_for_model", true));

        HttpEntity<Map<String, Object>> request = new HttpEntity<>(requestBody, headers);
        log.debug("Calling Stable Diffusion Image API at: {} with prompt: {}", imageApiUrl, enhancedPrompt);

        try {
            ResponseEntity<byte[]> responseEntity = restTemplate.exchange(imageApiUrl, HttpMethod.POST, request, byte[].class);
            if (responseEntity.getStatusCode().is2xxSuccessful() && responseEntity.getBody() != null) {
                byte[] imageBytes = responseEntity.getBody();
                log.info("Successfully received image bytes from Stable Diffusion API.");

                // Save the image and return its URL
                String filename = UUID.randomUUID().toString() + ".png";
                Path uploadPath = Paths.get(imageStorageLocation);
                if (!Files.exists(uploadPath)) {
                    Files.createDirectories(uploadPath);
                }
                Path filePath = uploadPath.resolve(filename);
                try {
                    Files.write(filePath, imageBytes);
                    String imageUrl = "/api/images/" + filename; // Use the same URL pattern as configured
                    log.info("Saved generated image to: {} | URL: {}", filePath, imageUrl);
                    return imageUrl;
                } catch (IOException e) {
                    log.error("Failed to save generated image: {}", filePath, e);
                }
            } else {
                log.error("Stable Diffusion Image API call failed with status: {} and body: {}", 
                    responseEntity.getStatusCode(), responseEntity.getBody());
            }
        } catch (Exception e) {
            log.error("Error calling Stable Diffusion Image API: {}", e.getMessage(), e);
        }
        
        // Fallback to placeholder if API call or saving fails
        return "/img/placeholder.png";
    }

    @Override
    public String getName() {
        return "Stable Diffusion";
    }

    @Override
    public String getProviderName() {
        return "Stable Diffusion";
    }

    @Override
    public String getApiUrl() {
        return imageApiUrl;
    }

    @Override
    public boolean supportsImageGeneration() {
        return apiKey != null && !apiKey.isEmpty();
    }
}
